### ISSUE TITLE
$ gh-description without arguments throws error

### ISSUE THREAD

**Issue by fregante** [RichardLitt/gh-description#7]
What request is this sending? What is does the command `gh-description` without any arguments do?

<img width="573" alt="screen shot 2017-02-05 at 15 38 22" src="https://cloud.githubusercontent.com/assets/1402241/22624251/af3bc632-eb2a-11e6-9efa-17fbcc8e0ad6.png">

This happens in a public git repo folder.

**Comment by RichardLitt** [comment]
Can you show me the output of `git remote -vv` in that folder?

**Comment by fregante** [comment]
```
origin	https://github.com/bfred-it/iphone-inline-video.git (fetch)
origin	https://github.com/bfred-it/iphone-inline-video.git (push)
```

**Comment by fregante** [comment]
This seems to be the error (`.git`)

<img width="453" alt="screen shot 2017-02-07 at 23 43 30" src="https://cloud.githubusercontent.com/assets/1402241/22695779/c493978a-ed00-11e6-870c-c2f30f058963.png">

**Comment by RichardLitt** [comment]
Working on it now. Replicated.

**Comment by RichardLitt** [comment]
Thanks for the help!
